$term = kitty
$browser = firefox
$fileManager = thunar
$statusBar = quickshell -c Hypno-Bar
$notifDaemon = dunst
$wallpaper = hyprpaper
$screenLock = gtklock
$menu = rofi -show drun
$powerMenu = loginctl terminate-session $XDG_SESSION_ID
