device {
	name = sino-wealth-bluetooth-keyboard
	kb_layout = us
}

device{
	name = sino-wealth-bluetooth-keyboard-1
	kb_layout = us
}
device{
	name = sino-wealth-bluetooth-keyboard-system-control
	kb_layout=us
}
device{
	name = sino-wealth-bluetooth-keyboard-consumer-control
	kb_layout=us
}

